### ISSUE TITLE
Fix reflect kills not counting toward killstreak if original projectile owner did not use a killstreak weapon.

### ISSUE THREAD

**Issue by CoolJosh3k** [mastercomfig/tf2-patches-old#120]
**Is your feature request related to a problem? Please describe.**
When scoring a reflect kill with a Pyro's airblast, for a killstreak counter to increment it requires the one who originally fired the projectile to have used a killstreak weapon.
If the reflect kill happens from a projectile that was not fired from a killstreak weapon, then no killstreak credit is given.

Killstreak flamethrower reflect kill + from a non-killstreak rocket launcher = no killstreak credit for you.
Killstreak flamethrower reflect kill + from a killstreak rocket launcher = yay, you scored a kill for your killstreak!

**Describe the solution you'd like**
When a pyro scores a reflect kill using a killstreak weapon, the killstreak count should increase without reguard to the original projectile owner.

Killstreak flamethrower reflect kill + from a non-killstreak rocket launcher =  yay, you scored a kill for your killstreak!
Killstreak flamethrower reflect kill + from a killstreak rocket launcher = yay, you scored a kill for your killstreak!

**Describe alternatives you've considered**
Continue to be sad that getting a high killstreak on Pyro is harder becuase of this bug.

**Additional context**
I have asked the TF Team if they could fix this in the past.
I'd hope it is a simple conditional for the weapon type, then replace the Owner with DeflectOwner.

**Comment by micwoj92** [comment]
@wgetJane wasnt that fixed?

**Comment by wgetJane** [comment]
> @wgetJane wasnt that fixed?

no

**Comment by micwoj92** [comment]
Ah thanks for clarification. I thought it was resolved alongside the airblast damage bug (y)

**Comment by CoolJosh3k** [comment]
Just loaded up tr_walkway in the normal TF2 and was able to confirm that the bug does indeed still exist.

Death by fire increases killstreak. Death by reflect does not, because the bots do not use killstreak weapons to fire the rockets/grenades.

**Comment by wgetJane** [comment]
@CoolJosh3k can you test if the following increases a killstreak weapon's kill count:

- reflect kills with rockets in tf2
- reflect kills with grenades in tf2
- reflect kills with rockets in tc2
- reflect kills with grenades in tc2

**Comment by treacherousfiend** [comment]
Didn't test live (yet) but seems to still be broken in comtress, my killstreak hasn't gone up, and it didn't show up as a killstreak in the killfeed.

It might be worthwhile to test spam airblasting pyro bots against ks grenade launcher and rocket launcher? I don't have either so I can't test

**Comment by treacherousfiend** [comment]
update, in live tf2, if the other player _doesn't_ have a ks weapon, then the pyro's ks works as expected. so its more broken in TC2 then it is in live

**Comment by Yttrium-tYcLief** [comment]
Anything broken in TC2 but working in TF2 should be (mostly) ignored. That being said, just to clarify - there *are* still parts of this issue that exist in both live TF2 *and* TC2?

**Comment by wgetJane** [comment]
@treacherousfiend can you say if the following increments a killstreak flamethrower's kill count?

>- reflect kills with rockets in tf2
>- reflect kills with grenades in tf2
>- reflect kills with rockets in tc2
>- reflect kills with grenades in tc2

i'm need to figure out if this is caused by this: https://github.com/mastercomfig/team-comtress-2/pull/17

my prediction would be:

- reflect kills with rockets in tf2: no
- reflect kills with grenades in tf2: yes
- reflect kills with rockets in tc2: no
- reflect kills with grenades in tc2: no

if this prediction is correct, then most likely the self-damage fix is related to this issue

**Comment by treacherousfiend** [comment]
hmmm, I forgot to test rockets in tf2, but grenades seem to work correctly?

I think in order to get to the bottom of this we'll need to have both players with ks weapons.

**Comment by wgetJane** [comment]
> I think in order to get to the bottom of this we'll need to have both players with ks weapons.

that's shouldn't be necessary for now, can you tell if the prediction is correct first

**Comment by CoolJosh3k** [comment]
Did some testing and recorded the following results.

TF2 Rockets: https://youtu.be/lzyrRpt5Zyg
TF2 Grenades: https://youtu.be/xK_0YhUwx14

TC2 Rockets: https://youtu.be/oucxe1W4hcw
TC2 Grenades: https://youtu.be/ZTBQIDkqyTA

So yes, reflected grenades work in TF2, but got broken in TC2.

I suggest a solution for this is not undoing the other fix, but instead implementing a fix that addresses all reflect kill streak credit.

**Comment by wgetJane** [comment]
@CoolJosh3k the videos you've linked are private btw

**Comment by CoolJosh3k** [comment]
Oh, whoops. I ment to have them unlisted. Fixed that now.

**Comment by mastercoms** [comment]
Fixed in new TC2
